### ISSUE TITLE
SERVIÇOS / MOBILE - Ícones pilares

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#19]
Modificar layout dos ícones para cada pilar de atuação conforme o PSD.

**Comment by amedtler** [comment]
Ajustado.

**Comment by EltonOppermann** [comment]
Conseguimos colocar o título em texto quando muda para os icones sem título?

**Comment by amedtler** [comment]
Tem como colocar, porém não ficará dentro da área "clicável".

**Comment by EltonOppermann** [comment]
Isso! Daí fica em cima do texto. Dá uma olhada no PSD que eu tinha previsto isso.

**Comment by amedtler** [comment]
Não tinha me ligado no layout. Achei que tu estava falando do botão. Ta feito.
