### ISSUE TITLE
QUEM SOMOS / GERAL - Filtro dos logos

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#20]
O filtro dos logos dos logos dos clientes fica bom para quase todos. Mas, por exemplo, no ABCCC que já é preto não se nota diferença no hover. Temos como também mexer na opacidade talvez? Assim eles ficariam mais cinzas e com o hover pretos.

**Comment by amedtler** [comment]
Não consegui melhorar o filtro. Acho que teremos que fazer com duas imagens, assim como está no site que o outro cara fez. Pode ser?

**Comment by EltonOppermann** [comment]
Cara, acho que pode ser então! Assim tenho mais controle de como ficará o site...

**Comment by amedtler** [comment]
Feito! Só adicionar os logos.
