### ISSUE TITLE
QUEM SOMOS / GERAL - Logos clientes

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#22]
Centralizar os logos dos clientes na tela. Mesma questão das resoluções intermediárias do trabalhos.

**Comment by amedtler** [comment]
ajustado.

**Comment by EltonOppermann** [comment]
Cara, aqui no mobile tá ok. Mas agora no desktop (960 ou mais) está com cinco colunas de logos. Não conseguimos deixar nas 6 colunas que eram antes?

**Comment by amedtler** [comment]
Ajustado.
