### ISSUE TITLE
TRABALHOS / GERAL - Carregar mais

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#25]
Melhor queo carregamento fique pelo clique no botão. Senão fica impossível de visualizar o footer.

**Comment by amedtler** [comment]
Estou me batendo bastante nessa questão. Falei com alguns amigos se já tinham aplicado essa função no plugin que estou utilizando e ninguém conseguiu. Também não encontrei muitas referências pela internet. Enfim... vou continuar tentando e aviso quando conseguir resolver. Até te peço o seguinte. Sei que vocês tem alguns temas comprados, dá uma olhada se algum deles tem essa função, pq não consigo visualizar os códigos diretamente no themeforest.

**Comment by EltonOppermann** [comment]
Coloquei lá no drop os dois templates mais completos que temos aqui... Aparentemente não tem a função de carregar mais, mas talvez te ajude em algo. Em último caso, podemos pensar em uma opção tipo a do portfólio do Zerif, que tem umas bolinhas... Só não queria usar uma paginação simples...
Se achares algum plugin ou algo do tipo para comprar, que seja barato, podemos comprar...

**Comment by amedtler** [comment]
Tchê! Ta foda! Tentei com várias maneiras, quando consigo o carregar, os filtros não funcionam, etc... 
Também falei com vários conhecidos da área e ninguém ainda conseguiu resolver essa bronca. 
Enfim... achei um tema barato com essa função. Com isso deve funcionar, tem interesse?
http://themeforest.net/item/tides-fullscreen-video-single-page-template/5957384?ref=tommusrhodus

Já perdi muito tempo com isso, acho que vale.

**Comment by EltonOppermann** [comment]
Segue em anexo o template!!

Em 16 de abril de 2015 23:40, amedtler notifications@github.com escreveu:

> Tchê! Ta foda! Tentei com várias maneiras, quando consigo o carregar, os
> filtros não funcionam, etc...
> Também falei com vários conhecidos da área e ninguém ainda conseguiu
> resolver essa bronca.
> Enfim... achei um tema barato com essa função. Com isso deve funcionar,
> tem interesse?
> 
> http://themeforest.net/item/tides-fullscreen-video-single-page-template/5957384?ref=tommusrhodus
> 
> Já perdi muito tempo com isso, acho que vale.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/amedtler/Viu-Multimidia/issues/25#issuecomment-93881557
> .

## 

_Elton Oppermann_
Viu Multimídia
(51) 3388.6000 / 9849.6149
www.viumultimidia.com.br

**Comment by amedtler** [comment]
Tchê! Fiz uma cagada. Esse template era apenas html e não para wordpress. 
Enfim, serviu para uma parte do problema, mas ainda não consegui concluir. Testei outros plugins, porém nem todos tem todas as funcionalidades que precisamos, então preciso continuar nesse mesmo. 
Trabalhei praticamente o findi inteiro nisso. Hoje consegui falar com um amigo que é fodão. Ficou de me dar uma força amanhã. Então espero que finalmente consiga resolver. Te aviso.

**Comment by amedtler** [comment]
Loco. A luta continua, nada ainda. Ontem passei o dia tentando resolver. Enfim... vou continuar tentando. Porém como vocês devem estar querendo lançar logo, pensei em uma alternativa. Veja se fica bom. Exibimos 9 o quantos posts quiserem na home, ao invés do botão carregar mais, colocamos carregar todos, ou mostrar todos. Ao clicar exibe todos. Dessa forma consigo fazer, inclusive sem reload na página. Qualquer coisa avisa. Abraço

**Comment by EltonOppermann** [comment]
Cara, temos pressa, mas não vai ser antes de segunda que vem. Vamos tentar
mais esse final de semana que terás mais tempo para fazer e semana que vem
decidimos.
Mas, provavelmente, se não for a função de carregar mais redonda, vamos
optar por uma paginação legal.
Segue me informando do status aí por favor.
Abs!
Elton.

Em 22 de abril de 2015 09:08, amedtler notifications@github.com escreveu:

> Loco. A luta continua, nada ainda. Ontem passei o dia tentando resolver.
> Enfim... vou continuar tentando. Porém como vocês devem estar querendo
> lançar logo, pensei em uma alternativa. Veja se fica bom. Exibimos 9 o
> quantos posts quiserem na home, ao invés do botão carregar mais, colocamos
> carregar todos, ou mostrar todos. Ao clicar exibe todos. Dessa forma
> consigo fazer, inclusive sem reload na página. Qualquer coisa avisa. Abraço
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/amedtler/Viu-Multimidia/issues/25#issuecomment-95151398
> .

## 

_Elton Oppermann_
Viu Multimídia
(51) 3388.6000 / 9849.6149
www.viumultimidia.com.br

**Comment by amedtler** [comment]
E ae loco. Finalmente consegui resolver essa parada. Só uma observação. 
Quando abre a página carrega apenas 9, se for clicar no botão carregar mais, vai carregar de 9 em 9. 
Se clicar em alguma categoria antes de ter carregado todos, vai exibir todos da categoria correspondente. Ok?

**Comment by EltonOppermann** [comment]
Tá ótimo...
