### ISSUE TITLE
RESPONSIVO GERAL

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#26]
Para as resoluções que te passei arte (768 - 320) está tudo perfeito. Só para algumas intermediárias, como 360 do S5, 600 do Kindle etc algumas merdas acontecem. Por exemplo, o menu principal quebra e escondem os links antes de entrar no formato 320.

**Comment by amedtler** [comment]
Ajustei bastante. Porém para que ficasse melhor, tive que fazer com que abaixo de 760 já pegue o modelo do mobile, assim não tem erro.

**Comment by EltonOppermann** [comment]
Tá ótimo!
