### ISSUE TITLE
TRABALHOS / GERAL - Slider

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#27]
Temos como mudar a transição do slider? Como ele é muito grande, 1920, fica demorado para percorrer toda a extensão horizontal. O ideal é que viesse de cima para baixo ou um fade.

**Comment by amedtler** [comment]
Ajustado para fade.

**Comment by EltonOppermann** [comment]
Aquele tempo que fica cinza no meio de um slide para outro, tem como diminuir? É carregamento?

**Comment by amedtler** [comment]
Na verdade esse plugin é feito somente para slider, isso que eu fiz foi uma gambiarra. Também não gostei. O que posso fazer e deixar mais rápido essa transição horizontal. De cima também não tem como fazer. Caso contrário terei que pesquisar outro script e fazer toda a adaptação para funcionar o fade.

**Comment by EltonOppermann** [comment]
Faz mais rápido a horizontal...
Se conseguires uma gambiarra para deixar vertical melhor. Senão deixa horizontal.

**Comment by amedtler** [comment]
Ficou na horizontal, porém mais rápido. Vou dar uma olhada se encontro outro script que possa utilizar a mesma estrutura, podendo aplicar o fade.

**Comment by EltonOppermann** [comment]
Oka
