### ISSUE TITLE
TRABALHOS / RESPONSIVO - Botão fechar

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#28]
Cara, não tinha visto isso... Mas quando o nome do projeto é grande o botão fechar está ficando em um lugar estranho nas versões mobile e tablet. Melhor que ele ficasse sempre alinha pela direita no topo do título e que o título quebrasse antes.
![captura de tela 2015-04-01 as 11 40 14](https://cloud.githubusercontent.com/assets/11294954/6943315/94ed200e-d863-11e4-81ba-8be63f5fb0c2.png)
![captura de tela 2015-04-01 as 11 40 03](https://cloud.githubusercontent.com/assets/11294954/6943318/97bf1300-d863-11e4-89a4-0880add581f8.png)

**Comment by amedtler** [comment]
Ajustado.

**Comment by amedtler** [comment]
Esqueci de ajustar o responsivo da página interna dos trabalhos abertos. Vou fazer agora.

**Comment by amedtler** [comment]
Ajustado.

**Comment by EltonOppermann** [comment]
360 tá massa!
no 320 ainda tá quebrando errado.
![captura de tela 2015-04-01 as 12 29 25](https://cloud.githubusercontent.com/assets/11294954/6944487/570ee1a8-d86a-11e4-95a5-815b493073a2.png)

**Comment by amedtler** [comment]
Acho que estava com cachê. Já tinha ajustado. Confere lá.
