### ISSUE TITLE
Case Sicredi

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#29]
Coloquei lá no drop box os PSDs para o case de Sicredi. O link para o vídeo é: http://youtu.be/7_sNWeDrdz8

**Comment by amedtler** [comment]
Ta feito. 
http://amdeveloper.com.br/clientes/viumultimidia/lancamento-cartoes-sicredi/
Duas observações: 
1 - A imagem do macbook tem uma sombra na lateral que estava para fora do grid. Então ficou um pouquinho diferente. 
2 - A parte que tem as 3 imagens alinhadas na versão tablet está com os padrões de alinhamento e espaço diferente, o que ficaria estranho no responsivo. Deixei uma ao lado da outra para não ficar ruim. Veja se está bom assim.

**Comment by EltonOppermann** [comment]
Ficou bom assim!
Só faltou o fullscreen no vídeo do youtube.
