### ISSUE TITLE
TRABALHOS / GERAL - Sliders

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#30]
Agora que coloquei os slides finais, deu pra ver que o slider continua dando uma piscada estranha de cinza. Tu ve que quando passa o de trás some antes do da frente completar o movimento...
Conseguiu ver aí?

**Comment by EltonOppermann** [comment]
Nos trabalhos tbm tem essa piscada nos sliders.

**Comment by amedtler** [comment]
Nos internos consegui resolver. Nos banners da home ainda está com esse problema. Estou fazendo alguns testes.

**Comment by EltonOppermann** [comment]
Coloquei lá no drop um slider que temos aqui comprado. Ve se te ajuda em algo.

**Comment by amedtler** [comment]
Instalei outro plugin para o slider. Nesse, não precisa criar 3 tamanhos, ele ajusta automático. Ele também cria automaticamente tamanho menor da imagem para o responsivo. Realmente ficou bem melhor. Ele tem vários formatos de transição, deixei randômico, mas pode ser definido somente fade se achar melhor. Inclusive o tempo de exibição e tempo de transição. Me avisa se ficou bom, depois te mostro como mexer nisso.
