### ISSUE TITLE
TRABALHOS / GERAL - Ordem

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#31]
Preciso que os trabalhos obedeçam o campo "ordem" que tem dentro do painel de cada um deles também na home do site. Agora, ele está colocando em ordem cronológica, mas as vezes preciso trocar essa ordem... Por exemplo, os dois últimos trabalhos inverti 27 e 28, trocou a ordem no painel, mas não no site.

**Comment by amedtler** [comment]
Instalei um plugin pra facilitar isso. 
Clica na opção trabalhos. Depois é só arrastar os trabalhos para cima ou para baixo para mudar a ordem. Não lembro como estava, mas pode ser que tenha mudado a ordem que tu tinha deixado.
