### ISSUE TITLE
TRABALHOS / INTERNO - Sliders

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#33]
Vamos colocar as bolinhas para baixo do slider e quando tiver apenas um slide não precisa bolinha.

**Comment by amedtler** [comment]
Ajustado.

**Comment by EltonOppermann** [comment]
Cara, esqueci de falar, mas quando é apenas um slide temos como tirar as setas tbm?

**Comment by amedtler** [comment]
Ajustado.
