### ISSUE TITLE
Migração

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#35]

**Comment by EltonOppermann** [comment]
Detalhes de Login

Usuário: viumulti
Senha: OD7wsN8tYzII

URL do Painel de Controle: http://108.167.188.185:2082/
Uma vez que seu domínio esteja propagado, você pode utilizar http://www.viumultimidia.com.br:2082/

Informações do Servidor

Server IP: 108.167.188.185

Caso esteja utilizando um domínio já existente com a sua nova conta de hospedagem, você precisa atualizar os DNS para apontar para os nossos servidores listados abaixo

NS1: ns1.webalex.com.br ()
NS2: ns2.webalex.com.br ()

Carregando seus arquivos no site

Temporariamente você pode usar um dos endereços abaixo indicados para atualizar o seu site:

Endereço de FTP temporário: 108.167.188.185
Endereço do Site temporário: http://108.167.188.185/~viumulti/

Uma vez que seu domínio esteja propagado você pode acessar da seguinte maneira:

Endereço de FTP: viumultimidia.com.br
Endereço do Site: http://www.viumultimidia.com.br

**Comment by amedtler** [comment]
Migração concluída.
