### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#38]
Está cadastrado?

**Comment by amedtler** [comment]
Sim.

**Comment by EltonOppermann** [comment]
Em qual e-mail tu cadastrou?

2015-05-04 16:21 GMT-03:00 amedtler notifications@github.com:

> Sim.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/amedtler/Viu-Multimidia/issues/38#issuecomment-98823827
> .

## 

_Elton Oppermann_
Viu Multimídia
(51) 3388.6000 / 9849.6149
www.viumultimidia.com.br

**Comment by amedtler** [comment]
viumultimidia@gmail.com

**Comment by amedtler** [comment]
Inclusive tu pode acessar lá e verificar se tem algum outro dado que queira retorno e precise ativar.
