### ISSUE TITLE
Resultado Google

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#39]
Dar uma ajeitada no resultado para a busca "viu multimídia".
Está só: Index of /. cgi-bin/ · novosite/ · teste/. Apache Server at www.viumultimidia.com.br Port 80.

Colocar descrição (quem somos), links, contato...

**Comment by amedtler** [comment]
Isso deve normalizar em 1 ou 2 dias até que o google faça nova verificação. 
No entanto vou adicionar um plugin que melhora isso.
