### ISSUE TITLE
Atalho Topo

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#42]
Outra coisa que estou sentindo falta no site, no mobile principalmente, é aquele botãozinho de atalho que fica no canto inferior direito para voltar ao topo. Tipo eese aqui: http://coletiva.net/
Muita mão fazer essa função?

**Comment by amedtler** [comment]
É tranquilo. Só me manda a arte que eu faço.

**Comment by EltonOppermann** [comment]
Segue a arte...
Daí o hover pode ser ele 100% de opacidade e normalmente pode deixá-lo 50%.
- --*
- Elton Oppermann*
  (51) 3388.6000 / 9849.6149

http://www.viumultimidia.com.br/
 Rua Marquês do Pombal, 1710 / 602 - CEP 90540-000
 Moinhos de Vento - Porto Alegre - RS - Brasil
https://www.facebook.com/viumultimidiabrasil
https://www.youtube.com/user/viumultimidia

2015-05-18 19:58 GMT-03:00 amedtler notifications@github.com:

**Comment by amedtler** [comment]
Faltou a arte.

**Comment by EltonOppermann** [comment]
Recebeu agora?

**Comment by amedtler** [comment]
Implementado.
