### ISSUE TITLE
Erros Trabalhos

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#44]
Cara, descobri um errinho de visualização dos sliders internos no iPhone 4S para baixo (4, 3...). Na orientação horizontal ele está cortando as imagens. (print 1).
Além disso, acho que desconfigurou a fonte do título "Trabalhos" quando se entra em um projeto. (print 2).
![print1](https://cloud.githubusercontent.com/assets/11294954/7837994/e6c7ea66-0460-11e5-8778-bb25852d552b.png)
![print2](https://cloud.githubusercontent.com/assets/11294954/7837997/eac6fa80-0460-11e5-90a8-0a04ff2818f1.png)

**Comment by amedtler** [comment]
Título ajustado. 
Meu iphone é 4s e não consegui reproduzir esse erro (cortando imagem). 
Funciona normalmente.

**Comment by EltonOppermann** [comment]
Dá uma olhada no emulador aquele: www.quirktools.com/screenfly
Não é por ele que vi antes, foi no cel do Mano, mas nele também acontece.
- --*
- Elton Oppermann*
  (51) 3388.6000 / 9849.6149

http://www.viumultimidia.com.br/
 Rua Marquês do Pombal, 1710 / 602 - CEP 90540-000
 Moinhos de Vento - Porto Alegre - RS - Brasil
https://www.facebook.com/viumultimidiabrasil
https://www.youtube.com/user/viumultimidia

2015-05-28 0:04 GMT-03:00 amedtler notifications@github.com:

**Comment by amedtler** [comment]
Realmente não consigo simular esse erro. Mesmo por esse simulador, abre normalmente.

**Comment by EltonOppermann** [comment]
Faz o seguinte... Entra no site no modo iPhone 3/4 vertical. Daí clica no
segundo trabalho, do flipbook do Sicredi. Daí rotaciona a tela para o modo
horizontal.
- --*
- Elton Oppermann*
  (51) 3388.6000 / 9849.6149

http://www.viumultimidia.com.br/
 Rua Marquês do Pombal, 1710 / 602 - CEP 90540-000
 Moinhos de Vento - Porto Alegre - RS - Brasil
https://www.facebook.com/viumultimidiabrasil
https://www.youtube.com/user/viumultimidia

2015-05-28 22:01 GMT-03:00 amedtler notifications@github.com:

**Comment by amedtler** [comment]
Ajustado.
