### ISSUE TITLE
Trabalhos - Layout tablet

### ISSUE THREAD

**Issue by EltonOppermann** [amedtler/Viu-Multimidia#46]
Tem duas coisas que estão ficando estranhas no layout do site na resolução de tablet, quando temos duas colunas de thumbs.

1 - O filtro fica meio desalinhado. Acho que quando quebrar para mais de uma linha, os botões podiam ficar alinhas pela esquerda como marquei no print abaixo.

![print1](https://cloud.githubusercontent.com/assets/11294954/8064970/b514eb28-0eb4-11e5-945a-b746eba87d26.jpg)

2 - Como ficam 9 trabalhos antes do carregar mais, fica 1 sozinho na linha no final. E pior, quando clica em carregar mais ele continua sozinho como no print abaixo. Não temos como deixar 8 trabalhos na resolução com duas colunas?

![print2](https://cloud.githubusercontent.com/assets/11294954/8064995/ddb28d38-0eb4-11e5-9408-905208afdfe3.jpg)

**Comment by amedtler** [comment]
1 - Ajustado, porém essa margem específica, coloquei apenas na resolução 768 (tablet). Pois tem que colocar em um único botão. Resolução abaixo vai continuar igual. Ou, se preferir, abaixo de 650 posso habilitar o menu mobile. 

2 - Ajustado, agora está carregando de 12 em 12.

**Comment by EltonOppermann** [comment]
1 - Vamos deixar abaixo de 650 com o menu mobile então.

**Comment by amedtler** [comment]
Esqueci dessa parte, faço hoje a noite.

**Comment by amedtler** [comment]
Ajustado.
